require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0.0
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Layout/LineLength:
  Description: 'Limit lines to 110 characters.'
  Max: 140
